CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(45) NOT NULL DEFAULT 'USER',
    qr BLOB
);

CREATE TABLE IF NOT EXISTS items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(45) NOT NULL,
    desc TEXT,
    start_price DOUBLE NOT NULL,
    image BLOB NOT NULL
);

CREATE TABLE IF NOT EXISTS auctions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    item INT NOT NULL,
    seller INT NOT NULL,
    start_price DOUBLE NOT NULL,
    min_increment DOUBLE NOT NULL DEFAULT 0.0,
    cur_bid INT DEFAULT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    state VARCHAR(45) DEFAULT NULL,
    FOREIGN KEY (item) REFERENCES items(id) ON DELETE RESTRICT,
    FOREIGN KEY (seller) REFERENCES users(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS bids (
    id INT AUTO_INCREMENT PRIMARY KEY,
    userid INT NOT NULL,
    auctionid INT NOT NULL,
    amt DOUBLE NOT NULL,
    time TIMESTAMP NOT NULL,
    FOREIGN KEY (userid) REFERENCES users(id) ON DELETE RESTRICT,
    FOREIGN KEY (auctionid) REFERENCES auctions(id) ON DELETE CASCADE
);

ALTER TABLE auctions ADD FOREIGN KEY (cur_bid) REFERENCES bids(id) ON DELETE SET NULL;
